### ISSUE TITLE
Local vs Remote Installation

### ISSUE THREAD

**Issue by uvaydovd** [tkn-tub/gr-gym#3]
Do I need to have both OpenAI Gym and GNU Radio installed on both local and remote machines if I want to use remote pipes? Or can I just install GNU Radio on one machine and OpenAI Gym on the other? For example I want my local machine with GPU capabilities to run the DRL agent so I would have OpenAI and all the python dependencies (I assume this means installing gr-gym as well) installed but I only install GNU Radio on the remote machine and not the local machine

**Comment by zubow** [comment]
You don't. In remote setup with two physical boxes you have to install GnuRadio on one box and OpenAIGym with our GrGym framework on the other box. For communication between the two boxes we recommend to use ZeroMQ sockets which are supported by our framework. So your mentioned configuration works fine.

**Comment by uvaydovd** [comment]
Thanks for the response! And just to clarify when you say install the GrGym framework you mean just the GrGym python module that is installed with pip3 and not the GrGym GNU Radio blocks?

**Comment by zubow** [comment]
Exactly.

**Comment by uvaydovd** [comment]
Thanks!
